/* Isolated Playwright regression test. Speech is captured, not played; no microphone. */
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'RobotLab.html'), 'utf8');
new Function(source.match(/<script>([\s\S]*?)<\/script>/)[1]);
const hooks = 'window.__tasks={get settings(){return settings},get state(){return state},generateLeveledChallenge,renderAll,challengeArrival,challengeAction,completeChallengeTarget,announceChallengeFailure,setMode};';
const html = source.replace('\n})();', '\n' + hooks + '\n})();');
const server = http.createServer((req, res) => {
  const file = path.resolve(root, '.' + decodeURIComponent(new URL(req.url, 'http://localhost').pathname));
  if (!file.startsWith(root + path.sep)) { res.writeHead(403).end(); return; }
  if (file === path.join(root, 'RobotLab.html')) { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(html); return; }
  if (!fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404).end(); return; }
  res.setHeader('Content-Type', {'.png':'image/png','.webp':'image/webp','.gif':'image/gif','.mp3':'audio/mpeg'}[path.extname(file)] || 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});
let browser;
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  browser = await chromium.launch({headless:true, executablePath:process.env.ROBOTLAB_CHROME || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const context = await browser.newContext({viewport:{width:1024,height:768},hasTouch:true});
  await context.addInitScript(() => {
    window.spokenTasks=[];window.taskUtterances=[];
    Object.defineProperty(speechSynthesis,'speak',{value:u=>{spokenTasks.push(u.text);taskUtterances.push(u)}});
    Object.defineProperty(speechSynthesis,'cancel',{value:()=>{}});
  });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/RobotLab.html?nombre=Prueba`);
  await page.waitForFunction(() => !!window.__tasks);
  await page.evaluate(() => {document.querySelector('#homeModal').classList.remove('show');__tasks.generateLeveledChallenge(6,false);});
  const boardRect = () => page.locator('#boardWrap').evaluate(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};});
  for(const viewport of [{width:1024,height:768},{width:768,height:1024}]){
    await page.setViewportSize(viewport);await page.locator('#boardWrap').scrollIntoViewIfNeeded();await page.waitForTimeout(350);
    if(await page.locator('#challengeTasksToggle').getAttribute('aria-expanded')==='true')await page.locator('#challengeTasksToggle').tap();
    const before=await boardRect();
    const availableWidth=await page.locator('.board-panel').evaluate(el=>{const s=getComputedStyle(el);return el.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight)});
    assert(Math.abs(before.width-availableWidth)<2,'tablet board uses the full width available in its column');
    assert(Math.abs(before.width-before.height)<2,'board remains square');
    assert(before.y>=0&&before.y+before.height<=viewport.height+1,'board fits vertically');
    assert(!(await page.locator('#boardHint').isVisible()),'level hint no longer consumes board height');
    assert.equal(await page.locator('#challengePrompt').evaluate(el=>getComputedStyle(el).position),'fixed');
    assert.equal(await page.locator('#challengePrompt').evaluate(el=>el.parentElement===document.body),true,'floating list is not clipped by a board or program panel');
    const footer=await page.locator('.board-controls').boundingBox();
    assert(footer.y>=before.y+before.height-1,'grid and infinite controls are below the board');
    assert(footer.y+footer.height<=viewport.height+1,'bottom controls remain onscreen');
    assert.equal(await page.locator('#statusPill').count(),0,'programming badge no longer takes space');
    await page.locator('#challengeTasksToggle').tap();
    assert(await page.locator('#challengeTasksBody').isVisible());
    assert.deepEqual(await boardRect(),before,'expanded task list never resizes or moves board');
    assert(await page.locator('#challengeTasksBody').evaluate(el=>getComputedStyle(el).touchAction==='pan-y'),'task list allows touch scrolling independently of the grid');
    assert(await page.locator('#challengeTasksToggle').evaluate(el=>el.getBoundingClientRect().height>=44),'toggle is touch friendly');
    if(process.env.ROBOTLAB_QA_DIR)await page.locator('.board-panel').screenshot({path:path.join(process.env.ROBOTLAB_QA_DIR,`floating-tasks-${viewport.width}.png`)});
    await page.locator('#challengeTasksToggle').tap();
    assert.deepEqual(await boardRect(),before,'collapsing leaves board unchanged');
  }
  console.log('PASS floating tasks expand/collapse with touch without reducing tablet board size');
  await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(350);
  assert((await boardRect()).width>=450,'normal tablet layout prioritizes a larger board without hiding the programming panels');
  await page.evaluate(()=>{__tasks.state.program=[{type:'forward',cat:'move',label:'⬆️ Avanzar'}];__tasks.renderAll();});
  const program=await page.evaluate(()=>JSON.stringify(__tasks.state.program));
  await page.locator('#maximizeBoard').tap();
  assert.equal(await page.locator('#maximizeBoardLabel').innerText(),'Volver');
  for(const viewport of [{width:1024,height:768},{width:768,height:1024},{width:480,height:800},{width:1920,height:1080}]){
    await page.setViewportSize(viewport);await page.waitForTimeout(350);
    const rect=await boardRect();
    assert(Math.abs(rect.width-rect.height)<2,'enlarged board stays square');
    assert(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=viewport.width+1&&rect.y+rect.height<=viewport.height+1,'enlarged board stays entirely onscreen after orientation changes');
    assert(rect.width>=Math.min(viewport.width,viewport.height)*.65,`enlarged board uses most of the screen: ${JSON.stringify({viewport,rect,layout:await page.locator('.board-panel').evaluate(el=>({width:el.clientWidth,height:el.clientHeight,position:getComputedStyle(el).position,box:el.getBoundingClientRect().toJSON(),head:el.querySelector('.board-head').offsetHeight,stage:el.querySelector('.board-stage').style.getPropertyValue('--board-fit')}))})}`);
    const anchored=await page.locator('#challengePrompt').boundingBox();
    assert(Math.abs(anchored.x-(rect.x+8))<2&&Math.abs(anchored.y-(rect.y+8))<2,`undragged task list follows the board when enlarging or rotating: ${JSON.stringify({rect,anchored})}`);
    if(viewport.width===1920)assert(rect.width>800,'large screens are not capped at 800px');
    if(viewport.width===1024&&process.env.ROBOTLAB_QA_DIR)await page.locator('.board-panel').screenshot({path:path.join(process.env.ROBOTLAB_QA_DIR,'maximized-board.png')});
  }
  await page.locator('#maximizeBoard').tap();
  assert.equal(await page.evaluate(()=>JSON.stringify(__tasks.state.program)),program,'returning restores the same program');
  await page.locator('#maximizeBoard').tap();await page.reload();await page.waitForFunction(()=>!!window.__tasks);
  await page.evaluate(()=>document.querySelector('#homeModal').classList.remove('show'));
  assert.equal(await page.evaluate(()=>__tasks.settings.boardMaximized),true,'enlarged view preference survives reload');
  await page.locator('#maximizeBoard').tap();await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(350);
  console.log('PASS larger tablet layout, fullscreen-sized square board, preserved program and saved view preference');
  await page.locator('#readChallengeTasks').tap();
  assert.match(await page.evaluate(()=>spokenTasks.at(-1)),/Visita/);
  const expectedTaskReading=await page.locator('.challenge-task span:last-child').allTextContents();
  assert.equal(await page.evaluate(()=>spokenTasks.at(-1)),`Tareas: ${expectedTaskReading.map((text,index)=>`${index+1}. ${text}`).join(' ')}`,'manual reading contains only numbered tasks, without the level or its title');
  assert(await page.locator('#challengeTasksBody').isVisible(),'manual reading opens the tasks while speaking');
  await page.evaluate(()=>taskUtterances.at(-1).onend());
  assert(!(await page.locator('#challengeTasksBody').isVisible()),'tasks retract when manual reading ends');
  await page.locator('#challengeTasksToggle').tap();
  await page.reload();await page.waitForFunction(()=>!!window.__tasks);
  await page.evaluate(()=>document.querySelector('#homeModal').classList.remove('show'));
  assert.equal(await page.locator('#challengeTasksToggle').getAttribute('aria-expanded'),'true','list preference survives reload');
  console.log('PASS manual reading and persistent task-list visibility');

  await page.evaluate(()=>{__tasks.settings.autoSpeak=1;__tasks.generateLeveledChallenge(6);});
  assert.match(await page.evaluate(()=>spokenTasks.at(-1)),/^Tareas: 1\..* 2\..* 3\./,'automatic reading starts with numbered tasks');
  assert.doesNotMatch(await page.evaluate(()=>spokenTasks.at(-1)),/\bNivel\b|Tres visitas en orden/,'automatic reading does not announce the level or its title');
  assert(await page.locator('#challengeTasksBody').isVisible(),'each new challenge opens the list during narration');
  const introBoard=await boardRect();
  const taskRect=()=>page.locator('#challengePrompt').evaluate(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}});
  const origin=await taskRect();
  assert(Math.abs(origin.x-(introBoard.x+8))<2&&Math.abs(origin.y-(introBoard.y+8))<2,'new challenge tasks begin over the board');
  await page.waitForTimeout(900);
  assert(await page.locator('#challengeTasksBody').isVisible(),'list does not retract before speech finishes');
  const grip=await page.locator('#challengeTasksDrag').boundingBox();
  await page.mouse.move(grip.x+22,grip.y+22);await page.mouse.down();
  await page.mouse.move(50,170,{steps:12});await page.mouse.up();
  const dragged=await taskRect();
  assert(dragged.x<100&&dragged.y>100,'list can move outside the board across the screen');
  assert.deepEqual(await boardRect(),introBoard,'dragging tasks does not affect the board');
  await page.evaluate(()=>__tasks.renderAll());
  assert.deepEqual(await taskRect(),dragged,'robot redraws preserve the chosen task position');
  const cdp=await context.newCDPSession(page),touchGrip=await page.locator('#challengeTasksDrag').boundingBox();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchGrip.x+22,y:touchGrip.y+22}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchGrip.x+172,y:touchGrip.y+102}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const touchDragged=await taskRect();
  assert(touchDragged.x>dragged.x+100&&touchDragged.y>dragged.y+50,'finger drag moves the panel instead of scrolling');
  await page.evaluate(()=>taskUtterances.at(-1).onend());
  assert(!(await page.locator('#challengeTasksBody').isVisible()));
  assert(Math.abs((await taskRect()).x-touchDragged.x)<2,'auto collapse stays where the student moved the list');
  await page.locator('#challengeTasksDrag').focus();await page.keyboard.press('ArrowLeft');
  assert((await taskRect()).x<touchDragged.x-15,'keyboard can also move the floating tasks');
  await page.evaluate(()=>{__tasks.generateLeveledChallenge(1);window.oldTaskSpeech=taskUtterances.at(-1);__tasks.generateLeveledChallenge(6);oldTaskSpeech.onend();});
  assert(await page.locator('#challengeTasksBody').isVisible(),'old speech completion cannot retract a newer challenge');
  const resetRect=await taskRect(),resetBoard=await boardRect();
  assert(Math.abs(resetRect.x-(resetBoard.x+8))<2&&Math.abs(resetRect.y-(resetBoard.y+8))<2,'each new challenge returns the tasks to the board');
  await page.evaluate(()=>taskUtterances.at(-1).onerror());
  assert(!(await page.locator('#challengeTasksBody').isVisible()),'speech failure also retracts tasks');
  await page.evaluate(()=>{__tasks.settings.autoSpeak=0;__tasks.generateLeveledChallenge(1);});
  assert(await page.locator('#challengeTasksBody').isVisible(),'without voice the student still sees the new tasks');
  await page.waitForFunction(()=>document.querySelector('#challengeTasksBody').hidden,{},{timeout:20000});
  assert(!(await page.locator('#challengeTasksBody').isVisible()),'without voice the list retracts after time to read');
  await cdp.detach();
  console.log('PASS mouse, finger and keyboard dragging; per-challenge reset; narration lifecycle and silent auto collapse');

  // Automatic reading uses its own setting, not the optional route help.
  let automaticBefore=await page.evaluate(()=>spokenTasks.length);
  await page.locator('#settingsBtn').click();
  await page.locator('#autoSpeak').selectOption('1');
  await page.locator('#helpLevel').selectOption('0');
  await page.locator('#previewRoute').uncheck();
  await page.locator('#speakNextTask').uncheck();
  await page.locator('#applySettings').click();
  assert.equal(await page.evaluate(()=>spokenTasks.length),automaticBefore+1,'enabling automatic reading immediately reads the open challenge');
  assert.match(await page.evaluate(()=>spokenTasks.at(-1)),/^Tareas: 1\./);
  assert(await page.locator('#challengeTasksBody').isVisible());
  await page.evaluate(()=>taskUtterances.at(-1).onend());
  automaticBefore=await page.evaluate(()=>spokenTasks.length);
  await page.evaluate(()=>{for(let i=0;i<4;i++)__tasks.renderAll()});
  await page.locator('#settingsBtn').click();await page.locator('#applySettings').click();
  assert.equal(await page.evaluate(()=>spokenTasks.length),automaticBefore,'redraws and unchanged settings do not repeat task reading');
  await page.locator('[data-mode="challenges"]').click();
  await page.locator('#genericContent [data-level="6"]').click();
  await page.locator('#generateLevelChallenge').click();
  assert.equal(await page.evaluate(()=>spokenTasks.length),automaticBefore+1,'the actual Generate challenge button reads the new tasks automatically');
  assert.match(await page.evaluate(()=>spokenTasks.at(-1)),/^Tareas: 1\..* 2\..* 3\./);
  await page.evaluate(()=>taskUtterances.at(-1).onend());
  await page.reload();await page.waitForFunction(()=>!!window.__tasks);
  assert.equal(await page.evaluate(()=>__tasks.settings.autoSpeak),1,'automatic reading stays enabled after reload');
  assert.equal(await page.evaluate(()=>spokenTasks.length),0,'tasks do not read behind the welcome screen');
  await page.locator('#homeModal [data-start="challenges"]').click();
  assert.equal(await page.evaluate(()=>spokenTasks.length),0,'task reading waits until challenge configuration is closed');
  await page.locator('#genericContent [data-close]').click();
  await page.waitForFunction(()=>spokenTasks.length===1);
  assert.match(await page.evaluate(()=>spokenTasks.at(-1)),/^Tareas: 1\./,'returning to the initial visible challenge reads its tasks once');
  await page.evaluate(()=>taskUtterances.at(-1).onend());
  await page.locator('[data-mode="challenges"]').click();await page.locator('#genericContent [data-close]').click();await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>spokenTasks.length),1,'reopening and closing configuration does not read the same challenge twice');
  await page.locator('#settingsBtn').click();await page.locator('#autoSpeak').selectOption('0');await page.locator('#applySettings').click();
  automaticBefore=await page.evaluate(()=>spokenTasks.length);
  await page.locator('[data-mode="challenges"]').click();await page.locator('#generateLevelChallenge').click();await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>spokenTasks.length),automaticBefore,'new tasks stay silent when automatic reading is off');
  console.log('PASS automatic task reading on activation, every generated challenge and restored initial challenge; no duplicates; independent of route help');

  const firstArrival = () => page.evaluate(() => {
    const ch=__tasks.state.challenge,t=ch.targets[0];__tasks.state.robot.c=t.c;__tasks.state.robot.r=t.r;__tasks.challengeArrival();__tasks.renderAll();
  });
  await page.evaluate(() => {__tasks.settings.autoSpeak=0;__tasks.settings.speakNextTask=true;__tasks.settings.help=1;__tasks.settings.preview=true;__tasks.generateLeveledChallenge(6,false);spokenTasks.length=0;});
  await firstArrival();
  assert.equal(await page.evaluate(()=>spokenTasks.length),0,'actual arrival does not read a construction hint');
  await page.evaluate(()=>{__tasks.completeChallengeTarget(__tasks.state.challenge.targets[0]);for(let i=0;i<5;i++)__tasks.renderAll();});
  assert.equal(await page.evaluate(()=>spokenTasks.length),0,'execution and rerenders do not read construction hints');
  await page.evaluate(()=>{const t=__tasks.state.challenge.targets[1];__tasks.state.robot.c=t.c;__tasks.state.robot.r=t.r;__tasks.challengeArrival();__tasks.renderAll();});
  assert.equal(await page.evaluate(()=>spokenTasks.length),0,'execution never reads the next construction task');
  for(const disabled of ['setting','help','route']){
    await page.evaluate(disabled=>{__tasks.settings.speakNextTask=disabled!=='setting';__tasks.settings.help=disabled==='help'?0:2;__tasks.settings.preview=disabled!=='route';__tasks.generateLeveledChallenge(6,false);spokenTasks.length=0;},disabled);
    await firstArrival();assert.equal(await page.evaluate(()=>spokenTasks.length),0,`${disabled} disables next-task narration`);
  }
  console.log('PASS real arrivals no longer read next-task construction guidance');

  await page.evaluate(()=>{__tasks.settings.speakNextTask=true;__tasks.settings.help=2;__tasks.settings.preview=true;__tasks.settings.challengeActionTypes=['noise'];__tasks.generateLeveledChallenge(8,false);spokenTasks.length=0;});
  await firstArrival();assert.equal(await page.evaluate(()=>spokenTasks.length),0,'arrival alone does not complete a required action');
  await page.evaluate(()=>{__tasks.challengeAction({type:'waitNoise'});__tasks.renderAll();});
  assert.equal(await page.evaluate(()=>spokenTasks.length),0,'executing a required action does not read construction guidance');
  console.log('PASS executing a challenge action does not trigger programming narration');
  const beforeFailure=await boardRect();
  await page.evaluate(()=>__tasks.announceChallengeFailure());
  assert.match(await page.locator('#challengeTaskFeedback').textContent(),/faltó/);
  assert.deepEqual(await boardRect(),beforeFailure,'failure feedback stays floating and does not shrink the board');
  await page.locator('#readChallengeTasks').tap();
  assert.match(await page.evaluate(()=>spokenTasks.at(-1)),/faltó/);
  console.log('PASS failure feedback remains available visually and by voice without resizing the board');

  await page.locator('#settingsBtn').click();
  await page.locator('#speakNextTask').uncheck();
  await page.locator('#applySettings').click();
  await page.reload();await page.waitForFunction(()=>!!window.__tasks);
  assert.equal(await page.evaluate(()=>__tasks.settings.speakNextTask),false);
  await page.evaluate(()=>{document.querySelector('#homeModal').classList.remove('show');__tasks.setMode('free');});
  assert(!(await page.locator('#challengePrompt').isVisible()));
  assert(await page.locator('#boardHint').isVisible());
  assert.deepEqual(errors,[]);
  console.log('PASS voice setting survives reload; free exploration restores its normal hint');
  await context.close();
  console.log('ALL FLOATING TASK TESTS PASSED');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
