const assert=require('node:assert/strict'),path=require('node:path');const {pathToFileURL}=require('node:url');const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const page=await browser.newPage({viewport:{width:768,height:1024},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.__spoken=[];window.__utterance=null;Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{cancel(){},speak(u){window.__utterance=u;window.__spoken.push(u.text);}}});});
await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.goto(pathToFileURL(path.resolve(__dirname,'../generador-oraciones.html')).href);await page.waitForFunction(()=>baseLista);await page.locator('[data-level="5"]').click();await page.locator('#celebrationSoundInput').uncheck();await page.locator('#startBtn').click();
async function answer(){await page.evaluate(()=>{stopSpeech();current={words:'Marta ve el barco en el río .'.split(' '),pics:['Marta','ver','barco','río'],mode:'connectors_free'};sentenceItems='Marta ve un barco en el río .'.split(' ').map((base,i)=>({base,text:i===0?capWord(base):base}));isSolved=false;checkAttempts=0;checkAnswer();});}
await answer();assert.equal((await page.evaluate(()=>window.__spoken)).at(-1),'Marta ve un barco en el río.');assert.equal(await page.locator('.interactive-stage').count(),0);assert.equal(await page.locator('#nextBtn').isDisabled(),true);assert.equal(await page.locator('#speakBtn').isDisabled(),true);
const before=await page.evaluate(()=>siguienteCelebracion);await page.evaluate(()=>checkAnswer());assert.equal(await page.evaluate(()=>siguienteCelebracion),before);
await page.waitForTimeout(1200);assert.equal(await page.locator('.interactive-stage').count(),0);
await page.evaluate(()=>window.__utterance.onend());await page.waitForSelector('.interactive-stage');assert.equal(await page.evaluate(()=>siguienteCelebracion),(before+1)%3);assert.equal(await page.locator('.interactive-object').count(),3);await page.locator('.interactive-continue').click();assert.equal(await page.locator('#nextBtn').isEnabled(),true);
await answer();await page.evaluate(()=>window.__utterance.onerror({error:'not-allowed'}));await page.waitForFunction(()=>!respuestaLeyendose);assert.equal(await page.locator('.interactive-stage').count(),0);assert.match(await page.locator('#speakBtn').textContent(),/Leer y celebrar/);await page.locator('#speakBtn').click();await page.evaluate(()=>window.__utterance.onend());await page.waitForSelector('.interactive-stage');await page.locator('.interactive-continue').click();
await answer();await page.evaluate(()=>{window.__oldUtterance=window.__utterance;});await page.locator('#backBtn').click();await page.evaluate(()=>window.__oldUtterance.onend());assert.equal(await page.locator('.interactive-stage').count(),0);assert.equal(await page.evaluate(()=>respuestaLeyendose),false);
await page.locator('#startBtn').click();await answer();await page.evaluate(()=>{window.__oldUtterance=window.__utterance;});await page.locator('#resetBtn').click();await page.evaluate(()=>window.__oldUtterance.onend());assert.equal(await page.locator('.interactive-stage').count(),0);assert.equal(await page.locator('#checkBtn').isEnabled(),true);
assert.deepEqual(errors,[]);console.log(JSON.stringify({actualSentence:'OK',waitForSpeechEnd:'OK',noOverlap:'OK',retry:'OK',cancelOnMenuOrReset:'OK'}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
